# Generated by Django 4.1 on 2022-12-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="email_address",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
