# Generated by Django 4.1 on 2022-12-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_author_email_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
